#! /bin/bash -x

CPP_STANDARD=c++17
INCLUDES=("-Iinclude/" "-I/usr/include/SDL2/" "-Itests/tools/Catch2/src/"
	"-Itests/tools/trompeloeil/include/" "-IDebug/generated-includes/")

clang-tidy "$@" -header-filter="include/remotemo|src/" -- -std=${CPP_STANDARD} ${INCLUDES[*]}
