name: CMake

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'
      
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install SDL2 (on ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev libsdl2-image-dev
      if: matrix.os == 'ubuntu-latest'
      
    - name: Install SDL2 (on MacOS)
      run: |
        brew update
        brew install sdl2 sdl2_image
      if: matrix.os == 'macos-latest'

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

