name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'
      
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  REMOTEMO_WERROR: ON
  REMOTEMO_BUILD_SAMPLES: ON
  REMOTEMO_BUILD_TESTS: ON
  REMOTEMO_VERBOSE_TESTS: OFF
  REMOTEMO_TESTS_COLOR: ON

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo OS
        run: |
          echo ${{ matrix.os }}
          echo $RUNNER_OS
          if [[ $RUNNER_OS == "Linux" ]]; then
            echo "This OS is a linux variant"
            echo $PATH
          elif [[ $RUNNER_OS == "macOS" ]]; then
            echo "This is a Mac"
            echo $PATH
          elif [[ $RUNNER_OS == "Windows" ]]; then
            echo "Ohh!... A Windows box"
            echo "Good for you"
          else
            echo "WHAT??? :O"
          fi
        shell: bash
