name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'
      
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  REMOTEMO_WERROR: ON
  REMOTEMO_BUILD_SAMPLES: ON
  REMOTEMO_BUILD_TESTS: ON
  REMOTEMO_VERBOSE_TESTS: OFF
  REMOTEMO_TESTS_COLOR: ON

jobs:
  test-matrix:
    strategy:
      fail-fast: false
      matrix:
        os_is: [linux, mac]
        os_variant: [1, 2]
        # [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
        include:
          - os_is: linux
            os_variant: 1
            os: ubuntu-20.04
          - os_is: linux
            os_variant: 2
            os: ubuntu-22.04
          - os_is: mac
            os_variant: 1
            os: macos-11
          - os_is: mac
            os_variant: 2
            os: macos-12
          - os_is: linux
            TEST_COMMAND: echo "This os is a linux variant"
            LONG_COMMAND: |
              echo "This is a test"
              echo "Can we do this?"
              ls
              echo "I hope so"
          - os_is: mac
            TEST_COMMAND: echo "This os is a MacOS variant"
            LONG_COMMAND: |
              echo "This is a test"
              echo "Can we do this?"
              ls
              echo "I hope so"
            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo OS
        run: |
          echo ${{ matrix.os }}
          ${{ matrix.TEST_COMMAND }}
      - name: test long command
        run: ${{ matrix.LONG_COMMAND }}
