name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'
      
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - '.github/workflow/*.yml'
      # re-include current file to not be excluded
      - '!.github/workflows/cmake.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  REMOTEMO_WERROR: ON
  REMOTEMO_BUILD_SAMPLES: ON
  REMOTEMO_BUILD_TESTS: ON
  REMOTEMO_VERBOSE_TESTS: OFF
  REMOTEMO_TESTS_COLOR: ON

jobs:
  test-matrix:
    env:
      LINUX_LONG_COMMAND: |
          echo "This os is a linux variant"
          echo "This is a test"
          echo "Can we do this?"
          echo "I hope so"
      MACOS_LONG_COMMAND: |
          echo "This os is a MacOS variant"
          echo "This is a test"
          echo "Can we do this?"
          echo "I hope so"
    strategy:
      fail-fast: false
      matrix:
        # os_is: [linux, mac]
        # os_variant: [1, 2]
        os: [ubuntu-20.04, ubuntu-22.04, macos-11, macos-12]
        include:
          - os: ubuntu-20.04
            LONG_COMMAND: ${{ env.LINUX_LONG_COMMAND }}
          - os: ubuntu-22.04
            LONG_COMMAND: ${{ env.LINUX_LONG_COMMAND }}
          - os: macos-11
            LONG_COMMAND: ${{ env.MACOS_LONG_COMMAND }}
          - os: macos-12
            LONG_COMMAND: ${{ env.MACOS_LONG_COMMAND }}
            
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo OS
        run: |
          echo ${{ matrix.os }}
#          ${{ matrix.TEST_COMMAND }}
      - name: test long command
        run: ${{ matrix.LONG_COMMAND }}
